### ISSUE TITLE
Gauges - Interaction

### ISSUE THREAD

**Issue by mfeckie** [hahuang65/beaker#11]
I'm wondering if it would make sense with the gauges to add the ability to set a min and max value?

This would be used for display purposes.  In my mind a gauge represents something like a speedometer or a bar of fix length.

It could either be defined on initialisation through a different arity call or it could be updated each time a result come in.

What do you think @hahuang65 ?

**Comment by hahuang65** [comment]
I think this is a great idea. Sorry I've been late to respond. Been a crazy week at work. I'll get to your PR very soon!

**Comment by hahuang65** [comment]
I think we can provide by default, infinite range, and if they call a different arity function to initialize, we can set bounds. Now, I'm not sure that if the value that comes in is outside of the bounds, do we still record it outside of the bounds but only report the lower/upper bound, or whether we don't record the value...

**Comment by mfeckie** [comment]
@hahuang65 No worry about taking time to respond!  Open source is hard and we all need a life :smile: 

As for the bounds, what would an infinite bound look like?  how would that be expressed in the code?

**Comment by hahuang65** [comment]
Not sure, the most naive thing would just to represent them as `nil` and handle accordingly in the code. There may be issues with that approach.
