### ISSUE TITLE
Time series and aggregation over time

### ISSUE THREAD

**Issue by mfeckie** [hahuang65/beaker#17]
So, Elixir / Erlang are high availability, so we could have a server with Beaker running for months / years without restart.

I've been playing locally and over time, the beaker_time_series_aggregator and beaker_time_series processes can grow to consume a lot of memory.  For example, after serving 60,000 requests, the beaker_time_series_aggregator is holding 13Mb of memory and beaker_time_series has 7.5Mb.

This seems to be because we keep everything.

I'm wondering if it's worth doing some work to limit the amount of data held permanently?  Something like a sliding window (http://blog.jonharrington.org/simple-sliding-windows-in-elixir/).  Seems like Erlang has us covered with `queue`.

What do you think?

**Comment by hahuang65** [comment]
Yups, I'm aware of this and have been considering how to resolve this. A sliding window might be a great idea and would work for most use cases. I've also considered using DETS to persist to disk, although I'll have to research that more.

The other thought I had was to switch the storage mechanism to something external like Redis, or just store it as a smaller binary protocol or something. The thing I don't like about using something like Redis is that I don't want to force users of Beaker to install another dependency.

Perhaps we can make a default sliding window, but for statistics that users might really want to keep indefinitely, we can pass an option to the initializer to mark it as a long-term metric?

**Comment by mfeckie** [comment]
I agree about Redis.  The beauty of Beaker for me was zero additional installation requirements.

I think sliding window as a starter would be good, with the option to offload to <some user chosen place>.  Initially I would be inclined to leave out the offload option and see how much desire/need there is for persistence.

**Comment by hahuang65** [comment]
I agree. I'll put together something in the next few days and I'll submit a PR for review. On another note, I was wondering if you'd like to join me as a collaborator on this project. You've been working really hard to bring some awesome features and was wondering if you'd be interested in continuing to work with me on this project?

**Comment by mfeckie** [comment]
Yes please :)

**Comment by hahuang65** [comment]
@mfeckie added! I'll make sure you're in the maintainers list in the next release also!

**Comment by hahuang65** [comment]
Gonna start working on this one in a couple of days.
