### ISSUE TITLE
Graphs not showing up by default?

### ISSUE THREAD

**Issue by hahuang65** [hahuang65/beaker#18]
I just tried the new Beaker in one of my pet projects and when I visit `/beaker` I no longer see the default Phoenix and Ecto graphs. Is there something I need to do to get those to show up?

Also, I noticed that `/beaker` itself will cause 2 requests on each API call. Perhaps we should mute that with regards to the request counter? What do you think?

**Comment by hahuang65** [comment]
Scratch that first question. It's just because I didn't have a full interval of data. But the second part still applies :)

**Comment by mfeckie** [comment]
Just so I understand, do you mean squash the requests into 1 or don't count them?

**Comment by hahuang65** [comment]
I meant "don't count them". Or at least segregate calls to `/beaker/api` into a different metric. This way we don't pollute users' namespaces but we can still see how Beaker is performing?

**Comment by mfeckie** [comment]
OK, on my way to work now.  Will take a look later :)

**Comment by mfeckie** [comment]
I think we'd need to make some changes here https://github.com/hahuang65/beaker/blob/master/lib/beaker/integrations/phoenix.ex in order to achieve it.  So skip count if request is scoped to API ?
