### ISSUE TITLE
Gauges not working on frontend without min/max

### ISSUE THREAD

**Issue by hahuang65** [hahuang65/beaker#19]
When you create a gauge in the backend without a min/max value, it displays an empty gauge on the frontend. We should either not display gauges without min/max, or figure out how we can visualize a gauge without a min/max setting.

My first thought is to just display a number, but I can understand how that's confusing to the user since it'll look like a counter. Perhaps a partially filled gauge?

Or do you think we should deprecate gauges without a min/max?

**Comment by mfeckie** [comment]
There are two ways I see.

1. Force min max as you say
2. Have the min max calculate dynamically on update.

Happy to explore either

**Comment by hahuang65** [comment]
I think 1 would be easier, but I'd love to hear you elaborate on what you mean with the second option?

**Comment by mfeckie** [comment]
So, I would imagine it being a change to the API.

Initially you "set" the counter, subsequently you "update" the counter.  When the update comes in, if value is less than previous, set min, if larger set max.

I thing, however, it would probably be best to go for option 1, option 2 could be considered longer term, if necessary.
