### ISSUE TITLE
Clear an individual TimeSeries/Counter

### ISSUE THREAD

**Issue by rockerBOO** [hahuang65/beaker#2]
Would it be possible to do this? I'm in the middle of development of something to check how to do it.

```elixir
key = "x"
TimeSeries.clear(key)
Counter.clear(key)
```

Right now I can set the counter to 0, but it still thinks it exists. If I give it `nil`, it crashes.

`Counter.set(key, nil)`

**Comment by hahuang65** [comment]
@rockerBOO Good idea. I'll have it implemented for next release.

**Comment by hahuang65** [comment]
Implemented in v0.0.4.
