### ISSUE TITLE
Skip calls to `/api` from registering into Beaker metrics

### ISSUE THREAD

**Issue by hahuang65** [hahuang65/beaker#22]
IMO we shouldn't count requests to Beaker (or at least separate it to it's own set of metrics) since it's not part of the user's application.

We might be able to simple pattern match against the `conn[:request_path]` in https://github.com/hahuang65/beaker/blob/master/lib/beaker/integrations/phoenix.ex#L11

**Comment by mgwidmann** [comment]
Why aren't phoenix channels used? Is it just a plug app?

Maybe it would be good to use phoenix for the front-end in order to utilize channels.

**Comment by mfeckie** [comment]
I considered this when building the API, but decided not to go down that path.  It's a dashboard, not expected to be consumed by many people and the number of requests is not huge.  Happy to consider revisiting this.

**Comment by mgwidmann** [comment]
it means that beaker's polling causes its own stats to go up like originally posted...
