### ISSUE TITLE
Non-"/beaker" URLs cause a black screen

### ISSUE THREAD

**Issue by mgwidmann** [hahuang65/beaker#23]
My `router.ex` has like this:

```
forward "/metrics", Beaker.Web
```

Which causes 
![image](https://cloud.githubusercontent.com/assets/5035724/12969618/0525cc64-d051-11e5-8882-4603e2d705fb.png)

Change it to:

```
forward "/beaker", Beaker.Web
```

and:

![image](https://cloud.githubusercontent.com/assets/5035724/12969630/23ef3f90-d051-11e5-808a-9707b2946307.png)

**Comment by mfeckie** [comment]
Hi @mgwidmann that's because the API that provides the data expects to get data from /beaker/api ...  Changing the mounted path means the api is no longer accessible from the expected path

**Comment by mgwidmann** [comment]
Yeah, I realized that... This means you cannot mount it where you want... The ember code shouldn't assume where beaker is mounter, rather use relative URL pathing to get to the API data.

**Comment by mfeckie** [comment]
@mgwidmann Happy to review a PR :)
