### ISSUE TITLE
TimeSeries in Minutes Instead of Milliseconds

### ISSUE THREAD

**Issue by rockerBOO** [hahuang65/beaker#3]
I am looking to do a TimeSeries in minute based precision, and then graph each minute up somewhere. The millisecond timestamp is too precise for that use.

Currently:
`{1435349460913762, 14}`

Ideally, not sure about the proper length
`{143534941, 14}`

Thanks again =)!

**Comment by hahuang65** [comment]
@rockerBOO so I'm working on the graph functionality right now. It'll probably be a few weeks before it's up.

The idea is that I'll average up each minute (or whatever interval) and graph that. All the developer will have to do is configure the page in their router.

That being said, if you'd like do to your own graphing, the timestamp provided in `Beaker.TimeSeries` is microsecond accuracy, so you'll need to truncate it by 6 places.
In your above example, it'd be `1435349460`.

**Comment by rockerBOO** [comment]
That sounds great with the average up to a time period. Glad you are already on top of it. =)

**Comment by hahuang65** [comment]
@rockerBOO I'm closing this ticket for now as it will be addressed in a future release. Hopefully I've answered your question enough that you can graph it on your own until that release?
