### ISSUE TITLE
JSON endpoint?

### ISSUE THREAD

**Issue by mfeckie** [hahuang65/beaker#8]
Would you be interested in an extension to this project to allow the stats to be served and consumed by either Highcharts on a JS refresh (as opposed to the full page refresh) or by other frontend resources?

**Comment by hahuang65** [comment]
Love the idea. I'm not a front end guy so I've had some challenges making a good front end happen for this.

**Comment by mfeckie** [comment]
I'll do a bit of work on it then and send you a PR :)

**Comment by mfeckie** [comment]
Also, this is a super useful project, so thanks for doing it so far :smile:

**Comment by hahuang65** [comment]
@mfeckie brilliant, thanks in advance for your hard work, and glad you find it useful :+1:
